package ambit2.reactions.retrosynth;

import java.util.ArrayList;
import java.util.List;

import org.openscience.cdk.interfaces.IAtomContainer;

public class ReactionSequenceLevel 
{
	public int levelIndex = 0;
	public ReactionSequenceLevel previousLevel = null;
	public ReactionSequenceLevel nextLevel = null;
	public List<ReactionSequenceStep> steps = new ArrayList<ReactionSequenceStep>(); 
	public List<IAtomContainer> molecules = new ArrayList<IAtomContainer>();
	
	public void removeMolecule(int index, boolean updateUpperLevels)
	{
		//Removes the molecule, the associated step and 
		//corresponding reaction subsequence
		molecules.remove(index);
		removeStep(index);
		if (updateUpperLevels)
		{	
			//TODO update up levels indices due to molecule removal
		}	
	}
	
	public void removeStep(int index)
	{
		//Removes the step 
		//and recursively all reaction subsequences generated by the step
		ReactionSequenceStep step = steps.get(index);
		steps.remove(index);
		
		if (step == null)
			return;
		//Remove subsequence generated by this step in down levels
		int indices[] = step.getOutMoleculesLevelIndices();
		for (int i = 0; i < indices.length; i++)
		{
			int k = indices[i];
			nextLevel.removeMolecule(k, false);
		}
	}
}
