var funcgroups = [
  { "family" :"" , "name":"Custom SMARTS" , "smarts" : "",  "hint" :"Enter the SMARTS in the text box, or draw in JME, using the QRY option"},
  { "family" :"alkane" , "name":"Alkyl carbon" , "smarts" :"[CX4]"},
  { "family" :"alkene (-ene)" , "name":"Allenic carbon" , "smarts" :"[$([CX2](=C)=C)]"},
  { "family" :"alkene (-ene)" , "name":"Vinylic carbon" , "smarts" :"[$([CX3]=[CX3])]"},
  { "family" :"alkyne (-yne)" , "name":"Acetylenic carbon" , "smarts" :"[$([CX2]#C)]"},
  { "family" :"arene (Ar , aryl-, aromatic hydrocarbons)" , "name":"Arene" , "smarts" :"c"},
  { "family" :"carbonyl" , "name":"Carbonyl group.Low specificity" , "smarts" :"[CX3]=[OX1]" , "hint" :"Hits carboxylic acid, ester, ketone, aldehyde, carbonic acid/ester,anhydride, carbamic acid/ester, acyl halide, amide"},

  { "family" :"carbonyl" , "name":"Carbonyl group" , "smarts" :"[$([CX3]=[OX1]),$([CX3+]-[OX1-])]" , "hint" :"Hits either resonance structure"},
  { "family" :"carbonyl" , "name":"Carbonyl with carbon" , "smarts" :"[CX3](=[OX1])C" , "hint" :"Hits aldehyde, ketone, carboxylic acid (except formic), anhydride (except formic), acyl halides (acid halides). Won't hit carbamic acid/ester, carbonic acid/ester"},
  { "family" :"carbonyl" , "name":"Carbonyl with nitrogen" , "smarts" :"[OX1]=CN" , "hint" :"Hits amide, carbamic acid/ester, poly peptide"},
  { "family" :"carbonyl" , "name":"Carbonyl with oxygen" , "smarts" :"[CX3](=[OX1])O" , "hint" :"Hits ester, carboxylic acid, carbonic acid or ester, carbamic acid or ester, anhydride Won't hit aldehyde or ketone"},
  { "family" :"carbonyl" , "name":"Acyl halide" , "smarts" :"[CX3](=[OX1])[F,Cl,Br,I]" , "hint" :"acid halide, -oyl halide"},
  { "family" :"carbonyl" , "name":"Aldehyde" , "smarts" :"[CX3H1](=O)[#6]" , "hint" :"-al"},
  { "family" :"carbonyl" , "name":"Anhydride" , "smarts" :"[CX3](=[OX1])[OX2][CX3](=[OX1])"},
  { "family" :"carbonyl" , "name":"Amide" , "smarts" :"[NX3][CX3](=[OX1])[#6]" , "hint" : "-amide"},
  { "family" :"carbonyl" , "name":"Amidinium" , "smarts" :"[NX3][CX3]=[NX3+]"},
  { "family" :"carbonyl" , "name":"Carbamate" , "smarts" :"[NX3,NX4+][CX3](=[OX1])[OX2,OX1-]" , "hint" :"Hits carbamic esters, acids, and zwitterions"},
  { "family" :"carbonyl" , "name":"Carbamic ester" , "smarts" :"[NX3][CX3](=[OX1])[OX2H0]"},
  { "family" :"carbonyl" , "name":"Carbamic acid" , "smarts" :"[NX3,NX4+][CX3](=[OX1])[OX2H,OX1-]" , "hint" :"Hits carbamic acids and zwitterions"},
  { "family" :"carbonyl" , "name":"Carboxylate ion" , "smarts" :"[CX3](=O)[O-]" , "hint" :"Hits conjugate bases of carboxylic, carbamic, and carbonic acids"},
  { "family" :"carbonyl" , "name":"Carbonic acid or carbonic ester" , "smarts" :"[CX3](=[OX1])(O)O" , "hint" :"Carbonic Acid, Carbonic Ester, or combination"},
  { "family" :"carbonyl" , "name":"Carbonic acid or carbonic acid-ester" , "smarts" :"[CX3](=[OX1])([OX2])[OX2H,OX1H0-1]" , "hint" :"Hits acid and conjugate base. Won't hit carbonic acid diester"},
  { "family" :"carbonyl" , "name":"Carbonic ester (carbonic acid diester)" , "smarts" :"C[OX2][CX3](=[OX1])[OX2]C" , "hint" :"Won't hit carbonic acid or combination carbonic acid/ester"},
  { "family" :"carbonyl" , "name":"Carboxylic acid" , "smarts" :"[CX3](=O)[OX2H1]" , "hint" :"-oic acid, COOH"},
  { "family" :"carbonyl" , "name":"Carboxylic acid or conjugate base" , "smarts" :"[CX3](=O)[OX1H0-,OX2H1]"},
  { "family" :"carbonyl" , "name":"Cyanamide" , "smarts" :"[NX3][CX2]#[NX1]"},
  { "family" :"carbonyl" , "name":"Ester(also hits anhydrides)" , "smarts" :"[#6][CX3](=O)[OX2H0][#6]" , "hint" :"won't hit formic anhydride"},
  { "family" :"carbonyl" , "name":"Ketone" , "smarts" :"[#6][CX3](=O)[#6]" , "hint" :"-one"},
  { "family" :"ether" , "name":"Ether" , "smarts" :"[OD2]([#6])[#6]" , "hint" :""},

  { "family" :"amine (-amino)" , "name":"Primary or secondary amine,not amide" , "smarts" :"[NX3;H2,H1;!$(NC=O)]" , "hint" :"Not ammonium ion (N must be 3-connected), not ammonia (H count can't be 3). Primary or secondary is specified by N's H-count (H2 and H1 respectively). Will hit cyanamides and thioamides"},

  { "family" :"amine (-amino)" , "name":"Enamine" , "smarts" :"[NX3][CX3]=[CX3]" , "hint" :""},
  { "family" :"amine (-amino)" , "name":"Primary amine,not amide" , "smarts" :"[NX3;H2;!$(NC=[!#6]);!$(NC#[!#6])][#6]" , "hint" :"Not amide (C not double bonded to a hetero-atom), not ammonium ion (N must be 3-connected), not ammonia (N's H-count can't be 3), not cyanamide (C not triple bonded to a hetero-atom)"},
  { "family" :"amine (-amino)" , "name":"Two primary or secondary amines" , "smarts" :"[NX3;H2,H1;!$(NC=O)].[NX3;H2,H1;!$(NC=O)]" , "hint" :"Here we use the disconnection symbol ('.') to match two separate unbonded identical patterns"},
  { "family" :"amine (-amino)" , "name":"Enamine or Aniline Nitrogen" , "smarts" :"[NX3][$(C=C),$(cc)]" , "hint" :""},
  { "family" :"amino acids" , "name":"Generic amino acid:low specificity" , "smarts" :"[NX3,NX4+][CX4H]([*])[CX3](=[OX1])[O,N]" , "hint" :"For use w/ non-standard a.a. search. hits pro but not gly. Hits acids and conjugate bases. Hits single a.a.s and specific residues w/in polypeptides (internal, or terminal)"},
    { "family" :"amino acids" , "name":"Amino acid " , "smarts" :"[$([NX3H2,NX4H3+]),$([NX3H](C)(C))][CX4H]([*])[CX3](=[OX1])[OX2H,OX1-,N]" , "hint" :"Replace * w/ a specific a.a. side chain from the 18 standard side chains list to hit a specific standard a.a. Won't work with Proline or Glycine, they have their own SMARTS (see side chain list). Hits acids and conjugate bases. Hits single a.a.s and specific residues w/i n polypeptides (internal, or terminal). {e.g. usage: Alanine side chain is [CH3X4] . Search is [$([NX3H2,NX4H3+]),$([NX3H](C)(C))][CX4H]([ CH3X4])[CX3](=[OX1])[OX2H,OX1-,N]}"},
  { "family" :"amino acid side chains" , "name":"Alanine side chain" , "smarts" :"[CH3X4]" , "hint" :""},
  { "family" :"amino acid side chains" , "name":"Arginine side chain" , "smarts" :"[CH2X4][CH2X4][CH2X4][NHX3][CH0X3](=[NH2X3+,NHX2+0])[NH2X3]" , "hint" :"Hits acid and conjugate base"},
  { "family" :"amino acid side chains" , "name":"Aspargine side chain" , "smarts" :"[CH2X4][CX3](=[OX1])[NX3H2]" , "hint" :"Also hits Gln side chain when used alone"},
  { "family" :"amino acid side chains" , "name":"Aspartate (or aspartic acid) side chain" , "smarts" :"[CH2X4][CX3](=[OX1])[OH0-,OH]" , "hint" :"Hits acid and conjugate base. Also hits Glu side chain when used alone. "},
  { "family" :"amino acid side chains" , "name":"Cysteine side chain" , "smarts" :"[CH2X4][SX2H,SX1H0-]" , "hint" :"Hits acid and conjugate base"},
  { "family" :"amino acid side chains" , "name":"Glutamate (or glutamic acid) side chain" , "smarts" :"[CH2X4][CH2X4][CX3](=[OX1])[OH0-,OH]" , "hint" :"Hits acid and conjugate base"},

  { "family" :"azide (-azido)" , "name":"Azide group" , "hint" :"Hits any atom with an attached azide" , "smarts" :"[$(*-[NX2-]-[NX2+]#[NX1]),$(*-[NX2]=[NX2+]=[NX1-])]"},
  { "family" :"azide (-azido)" , "name":"Azide ion" , "smarts" :"[$([NX1-]=[NX2+]=[NX1-]),$([NX1]#[NX2+]-[NX1-2])]" , "hint" :"Hits N in azide ion"},

  { "family" :"azo" , "name":"A nitrogen" , "smarts" :"[#7]" , "hint" :"Nitrogen in N-containing compound. aromatic or aliphatic. Most general interpretation of 'azo'"},
  { "family" :"azo" , "name":"Azo nitrogen. Low specificity" , "smarts" :"[NX2]=N" , "hint" :"Hits diazene, azoxy and some diazo structures"},
  { "family" :"azo" , "name":"Azo nitrogen.diazene" , "smarts" :"[NX2]=[NX2]" , "hint" :"(diaza alkene)"},
  { "family" :"azo" , "name":"Azoxy nitrogen" , "smarts" :"[$([NX2]=[NX3+]([O-])[#6]),$([NX2]=[NX3+0](=[O])[#6])]]" , "hint" :""},
  { "family" :"azo" , "name":"Diazo nitrogen" , "smarts" :"[$([#6]=[N+]=[N-]),$([#6-]-[N+]#[N])]"},
  { "family" :"azo" , "name":"Azole" , "smarts" :"[$([nr5]:[nr5,or5,sr5]),$([nr5]:[cr5]:[nr5,or5,sr5])]" , "hint" :"5 member aromatic heterocycle w/ 2double bonds. contains N and another non C (N,O,S) subclasses are furo-, thio-, pyrro- (replace CH o' furfuran, thiophene, pyrrol w/ N) "},

  { "family" :"hydrazine" , "name":"Hydrazine H2NNH2" , "smarts" :"[NX3][NX3]" , "hint" :""},
  { "family" :"hydrazone" , "name":"Hydrazone C=NNH2" , "smarts" :"[NX3][NX2]=[*]" , "hint" :""},
  { "family" :"imine" , "name":"Substituted imine" , "smarts" :"[CX3;$([C]([#6])[#6]),$([CH][#6])]=[NX2][#6]" , "hint" :"Schiff base"},
  { "family" :"imine" , "name":"Substituted or un-substituted imine " , "smarts" :"[$([CX3]([#6])[#6]),$([CX3H][#6])]=[$([NX2][#6]),$([NX2H])]" , "hint" :""},
  { "family" :"imine" , "name":"Iminium" , "smarts" :"[NX3+]=[CX3]" , "hint" :""},
  { "family" :"imide" , "name":"Unsubstituted dicarboximide" , "smarts" :"[CX3](=[OX1])[NX3H][CX3](=[OX1])" , "hint" :""},
  { "family" :"imide" , "name":"Substituted dicarboximide" , "smarts" :"[CX3](=[OX1])[NX3H0]([#6])[CX3](=[OX1])" , "hint" :""},
  { "family" :"imide" , "name":"Dicarboxdiimide " , "smarts" :"[CX3](=[OX1])[NX3H0]([NX3H0]([CX3](=[OX1]))[CX3](=[OX1]))[CX3](=[OX1])" , "hint" :""},

  { "family" :"nitrate" , "name":"Nitrate group" , "smarts" :"[$([NX3](=[OX1])(=[OX1])O),$([NX3+]([OX1-])(=[OX1])O)]" , "hint" :"Also hits nitrate anion"},
  { "family" :"nitrate" , "name":"Nitrate anion " , "smarts" :"[$([OX1]=[NX3](=[OX1])[OX1-]),$([OX1]=[NX3+]([OX1-])[OX1-])]" , "hint" :""},
  { "family" :"nitrile" , "name":"Nitrile" , "smarts" :"[NX1]#[CX2]" , "hint" :""},
  { "family" :"nitrile" , "name":"Isonitrile " , "smarts" :"[CX1-]#[NX2+]" , "hint" :""},
  { "family" :"nitro" , "name":"Nitro group" , "smarts" :"[$([NX3](=O)=O),$([NX3+](=O)[O-])][!#8]" , "hint" :"Hits both forms"},
  { "family" :"nitro" , "name":"Two nitro groups" , "smarts" :"[$([NX3](=O)=O),$([NX3+](=O)[O-])][!#8].[$([NX3](=O)=O),$([NX3+](=O)[O-])][!#8]" , "hint" :""},

  { "family" :"nitroso" , "name":"Nitroso group" , "smarts" :"[NX2]=[OX1]" , "hint" :""},
  { "family" :"n-oxide" , "smarts" :"[$([#7+][OX1-]),$([#7v5]=[OX1]);!$([#7](~[O])~[O]);!$([#7]=[#7])]" , "name":"N-Oxide" , "hint" :"Hits both forms. Won't hit azoxy, nitro, nitroso,or nitrate"},
  { "family" :"hydroxyl (includes alcohol, phenol)" , "name":"Hydroxyl" , "smarts" :"[OX2H]" , "hint" :""},
  { "family" :"hydroxyl (includes alcohol, phenol)" , "name":"Hydroxyl in alcohol" , "smarts" :"[#6][OX2H]" , "hint" :""},
  { "family" :"hydroxyl (includes alcohol, phenol)" , "name":"Hydroxyl in carboxylic acid" , "smarts" :"[OX2H][CX3]=[OX1]" , "hint" :""},
  { "family" :"hydroxyl (includes alcohol, phenol)" , "name":"Hydroxyl in H-O-P-" , "smarts" :"[OX2H]P" , "hint" :""},
  { "family" :"hydroxyl (includes alcohol, phenol)" , "name":"Enol" , "smarts" :"[OX2H][#6X3]=[#6]" , "hint" :""},
  { "family" :"hydroxyl (includes alcohol, phenol)" , "name":"Phenol" , "smarts" :"[OX2H][cX3]:[c]" , "hint" :""},
  { "family" :"hydroxyl (includes alcohol, phenol)" , "name":"Enol or phenol" , "smarts" :"[OX2H][$(C=C),$(cc)]" , "hint" :""},
  { "family" :"hydroxyl (includes alcohol, phenol)" , "name":"Hydroxyl acidic" , "smarts" :"[$([OH]-*=[!#6])]" , "hint" :"An acidic hydroxyl is a hydroxyl bonded to an atom which is multiply bonded to a hetero atom, this includes carboxylic, sulphur, phosphorous, halogen and nitrogen oxyacids"},

  { "family" :"peroxide" , "name":"Peroxide groups" , "smarts" :"[OX2,OX1-][OX2,OX1-]" , "hint" :"Also hits anions"},
  { "family" :"phosphoric compounds" , "name":"Phosphoric acid groups" , "smarts" :"[$(P(=[OX1])([$([OX2H]),$([OX1-]),$([OX2]P)])([$([OX2H]),$([OX1-]),$([OX2]P)])[$([OX2H]),$([OX1-]),$([OX2]P)]),$([P+]([OX1-])([$([OX2H]),$([OX1-]),$([OX2]P)])([$([OX2H]),$([OX1-]),$([OX2]P)])[$([OX2H]),$([OX1-]),$([OX2]P)])]" , "hint" :"Hits both depiction forms. Hits orthophosphoric acid and polyphosphoric acid anhydrides. Doesn't hit monophosphoric acid anhydride esters (including acidic mono- and di- esters) but will hit some polyphosphoric acid anhydride esters (mono- esters on pyrophosphoric acid and longer, di- esters on linear triphosphoric acid and longer)"},
  { "family" :"phosphoric compounds" , "name":"Phosphoric ester groups" , "smarts" :"[$(P(=[OX1])([OX2][#6])([$([OX2H]),$([OX1-]),$([OX2][#6])])[$([OX2H]),$([OX1-]),$([OX2][#6]),$([OX2]P)]),$([P+]([OX1-])([OX2][#6])([$([OX2H]),$([OX1-]),$([OX2][#6])])[$([OX2H]),$([OX1-]),$([OX2][#6]),$([OX2]P)])]" , "hint" :"Hits both depiction forms. Doesn't hit non-ester phosphoric acid groups"},

  { "family" :"thio groups ( thio-, thi-, sulpho-, mercapto- )" , "name":"Carbo thiocarboxylate " , "smarts" :"[S-][CX3](=S)[#6]" , "hint" :""},
  { "family" :"thio groups ( thio-, thi-, sulpho-, mercapto- )" , "name":"Carbo thioester" , "smarts" :"S([#6])[CX3](=O)[#6]" , "hint" :""},
  { "family" :"thio groups ( thio-, thi-, sulpho-, mercapto- )" , "name":"Thio analog of carbonyl" , "smarts" :"[#6X3](=[SX1])([!N])[!N] " , "hint" :"Where S replaces O. Not a thioamide"},
  { "family" :"thio groups ( thio-, thi-, sulpho-, mercapto- )" , "name":"Thiol, sulfide or disulfide sulfur" , "smarts" :"[SX2]" , "hint" :""},
  { "family" :"thio groups ( thio-, thi-, sulpho-, mercapto- )" , "name":"Thiol" , "smarts" :"[#16X2H]" , "hint" :""},
  { "family" :"thio groups ( thio-, thi-, sulpho-, mercapto- )" , "name":"Sulfur with at least one hydrogen" , "smarts" :"[#16!H0]" , "hint" :""},
  { "family" :"thio groups ( thio-, thi-, sulpho-, mercapto- )" , "name":"Thioamide" , "smarts" :"[NX3][CX3]=[SX1]" , "hint" :""},

  { "family" :"sulfide" , "name":"Sulfide" , "smarts" :"[#16X2H0]" , "hint" :"-alkylthio Won't hit thiols. Hits disulfides"},
  { "family" :"sulfide" , "name":"Mono sulfide" , "smarts" :"[#16X2H0][!#16]" , "hint" :"alkylthio- or alkoxy- Won't hit thiols. Won't hit disulfides"},
  { "family" :"sulfide" , "name":"Disulfide" , "smarts" :"[#16X2H0][#16X2H0]" , "hint" :"Won't hit thiols. Won't hit mono-sulfides"},
  { "family" :"sulfide" , "name":"Two sulfides" , "smarts" :"[#16X2H0][!#16].[#16X2H0][!#16]" , "hint" :"Won't hit thiols. Won't hit mono-sulfides. Won't hit disulfides"},

  { "family" :"sulfinate" , "name":"Sulfinate" , "smarts" :"[$([#16X3](=[OX1])[OX2H0]),$([#16X3+]([OX1-])[OX2H0])]" , "hint" :"Won't hit Sulfinic Acid. Hits Both Depiction Forms"},
  { "family" :"sulfinate" , "name":"Sulfinic acid" , "smarts" :"[$([#16X3](=[OX1])[OX2H,OX1H0-]),$([#16X3+]([OX1-])[OX2H,OX1H0-])]" , "hint" :"Won't hit substituted Sulfinates. Hits Both Depiction Forms. Hits acid and conjugate base (sulfinate)"},


  { "family" :"sulfone" , "name":"Sulfone: low specificity" , "smarts" :"[$([#16X4](=[OX1])=[OX1]),$([#16X4+2]([OX1-])[OX1-])]" , "hint" :"Hits all sulfones, including heteroatom-substituted sulfones: sulfonic acid, sulfonate, sulfuric acid mono- and di- esters, sulfamic acid, sulfamate, sulfonamide... Hits Both Depiction Forms"},
  { "family" :"sulfone" , "name":"Sulfone: high specificity" , "smarts" :"[$([#16X4](=[OX1])(=[OX1])([#6])[#6]),$([#16X4+2]([OX1-])([OX1-])([#6])[#6])]" , "hint" :"Only hits carbo- sulfones (Won't hit herteroatom-substituted molecules). Hits Both Depiction Forms"},
  { "family" :"sulfone" , "name":"Sulfonic acid: high specificity" , "smarts" :"[$([#16X4](=[OX1])(=[OX1])([#6])[OX2H,OX1H0-]),$([#16X4+2]([OX1-])([OX1-])([#6])[OX2H,OX1H0-])]" , "hint" :"Only hits carbo- sulfonic acids (Won't hit herteroatom-substituted molecules). Hits acid and conjugate base. Hits Both Depiction Forms. Hits Arene sulfonic acids"},
  { "family" :"sulfone" , "name":"Sulfonate" , "smarts" :"[$([#16X4](=[OX1])(=[OX1])([#6])[OX2H0]),$([#16X4+2]([OX1-])([OX1-])([#6])[OX2H0])]" , "hint" :"(sulfonic ester) Only hits carbon-substituted sulfur (Oxygen may be herteroatom-substituted). Hits Both Depiction Forms"},
  { "family" :"sulfone" , "name":"Sulfonamide" , "smarts" :"[$([#16X4]([NX3])(=[OX1])(=[OX1])[#6]),$([#16X4+2]([NX3])([OX1-])([OX1-])[#6])]" , "hint" :"Only hits carbo- sulfonamide. Hits Both Depiction Forms"},
  { "family" :"sulfone" , "name":"Carbo-azosulfone" , "smarts" :"[SX4](C)(C)(=O)=N" , "hint" :"Partial N-Analog of Sulfone"},
  { "family" :"sulfone" , "name":"Sulfonamide" , "smarts" :"[$([SX4](=[OX1])(=[OX1])([!O])[NX3]),$([SX4+2]([OX1-])([OX1-])([!O])[NX3])]" , "hint" :"(sulf drugs) Won't hit sulfamic acid or sulfamate. Hits Both Depiction Forms"},
  { "family" :"sulfoxide" , "name":"Sulfoxide: low specificity" , "smarts" :"[$([#16X3]=[OX1]),$([#16X3+][OX1-])]" , "hint" :"( sulfinyl, thionyl ) Analog of carbonyl where S replaces C. Hits all sulfoxides, including heteroatom-substituted sulfoxides, dialkylsulfoxides carbo-sulfoxides, sulfinate, sulfinic acids... Hits Both Depiction Forms. Won't hit sulfones"},
  { "family" :"sulfoxide" , "name":"Sulfoxide: high specificity" , "smarts" :"[$([#16X3](=[OX1])([#6])[#6]),$([#16X3+]([OX1-])([#6])[#6])]" , "hint" :"(sulfinyl , thionyl) Analog of carbonyl where S replaces C. Only hits carbo-sulfoxides (Won't hit herteroatom-substituted molecules). Hits Both Depiction Forms. Won't hit sulfones"},

  { "family" :"sulfate" , "name":"Sulfate" , "smarts" :"[$([#16X4](=[OX1])(=[OX1])([OX2H,OX1H0-])[OX2][#6]),$([#16X4+2]([OX1-])([OX1-])([OX2H,OX1H0-])[OX2][#6])]" , "hint" :"(sulfuric acid monoester) Only hits when oxygen is carbon-substituted. Hits acid and conjugate base. Hits Both Depiction Forms"},
  { "family" :"sulfate" , "name":"Sulfuric acid ester: low specificity" , "smarts" :"[$([SX4](=O)(=O)(O)O),$([SX4+2]([O-])([O-])(O)O)]" , "hint" :"Hits sulfuric acid, sulfuric acid monoesters (sulfuric acids) and diesters (sulfates). Hits acid and conjugate base. Hits Both Depiction Forms"},
  { "family" :"sulfate" , "name":"Sulfuric acid Diester" , "smarts" :"[$([#16X4](=[OX1])(=[OX1])([OX2][#6])[OX2][#6]),$([#16X4](=[OX1])(=[OX1])([OX2][#6])[OX2][#6])]" , "hint" :"Only hits when oxygen is carbon-substituted. Hits Both Depiction Forms"},

  { "family" :"sulfamate" , "name":"Sulfamate" , "smarts" :"[$([#16X4]([NX3])(=[OX1])(=[OX1])[OX2][#6]),$([#16X4+2]([NX3])([OX1-])([OX1-])[OX2][#6])]" , "hint" :"Only hits when oxygen is carbon-substituted. Hits Both Depiction Forms"},
  { "family" :"sulfamate" , "name":"Sulfamic acid" , "smarts" :"[$([#16X4]([NX3])(=[OX1])(=[OX1])[OX2H,OX1H0-]),$([#16X4+2]([NX3])([OX1-])([OX1-])[OX2H,OX1H0-])]" , "hint" :"Hits acid and conjugate base. Hits Both Depiction Forms"},
  { "family" :"sulfene" , "name":"Sulfenic acid" , "smarts" :"[#16X2][OX2H,OX1H0-]" , "hint" :"Hits acid and conjugate base"},
  { "family" :"sulfene" , "name":"Sulfenate" , "smarts" :"[#16X2][OX2H0]" , "hint" :""},

  { "family" :"Halide (-halo -fluoro -chloro -bromo -iodo)" , "name":"Any carbon attached to any halogen" , "smarts" :"[#6][F,Cl,Br,I]" , "hint" :""},
  { "family" :"Halide (-halo -fluoro -chloro -bromo -iodo)" , "name":"Halogen" , "smarts" :"[F,Cl,Br,I]" , "hint" :""},
  { "family" :"Halide (-halo -fluoro -chloro -bromo -iodo)" , "name":"Three halides groups" , "smarts" :"[F,Cl,Br,I].[F,Cl,Br,I].[F,Cl,Br,I]" , "hint" :"Hits SMILES that have three halides"},
  { "family" :"Acyl halide" , "name":"Acyl Halide" , "smarts" :"[CX3](=[OX1])[F,Cl,Br,I]" , "hint" :"(acid halide, -oyl halide)"},

  { "family" :"Acids and Bases" , "name":"Acid" , "smarts" :"[!H0;F,Cl,Br,I,N+,$([OH]-*=[!#6]),+]" , "hint" :"Proton donor"},
  { "family" :"Acids and Bases" , "name":"Carboxylic acid" , "smarts" :"[CX3](=O)[OX2H1]" , "hint" :"(-oic acid, COOH)"},
  { "family" :"Acids and Bases" , "name":"Carboxylic acid or conjugate base" , "smarts" :"[CX3](=O)[OX1H0-,OX2H1]" , "hint" :""},
  { "family" :"Acids and Bases" , "name":"Hydroxyl acidic" , "smarts" :"[$([OH]-*=[!#6])]" , "hint" :"An acidic hydroxyl is a hydroxyl bonded to an atom which is multiply bonded to a hetero atom, this includes carboxylic, sulphur, pho sphorous, halogen and nitrogen oxyacids "},
  { "family" :"Acids and Bases" , "name":"Phosphoric Acid" , "smarts" :"[$(P(=[OX1])([$([OX2H]),$([OX1-]),$([OX2]P)])([$([OX2H]),$([OX1-]),$([OX2]P)])[$([OX2H]),$([OX1-]),$([OX2]P)]),$([P+]([OX1-])([$([OX2H]),$([OX1-]),$([OX2]P)])([$([OX2H]),$([OX1-]),$([OX2]P)])[$([OX2H]),$([OX1-]),$([OX2]P)])]" , "hint" :"Hits both forms. Hits orthophosphoric acid and polyphosphoric acid anhydrides. Doesn't hit monophosphoric acid anhydride esters (in cluding acidic mono- and di- esters) but will hit some polyphosphoric acid anhydride esters (mono- esters on pyrophosphoric acid and longe r, di- esters on linear triphosphoric acid and longer). Hits acid and conjugate base"},
  { "family" :"Acids and Bases" , "name":"Sulfonic Acid: high specificity" , "smarts" :"[$([#16X4](=[OX1])(=[OX1])([#6])[OX2H,OX1H0-]),$([#16X4+2]([OX1-])([OX1-])([#6])[OX2H,OX1H0-])]" , "hint" :"Only hits carbo- sulfonic acids (Won't hit herteroatom-substituted molecules). Hits acid and conjugate base. Hits Both Depiction Fo rms. Hits Arene sulfonic acids"}
];