package ambit2.rest.structure.diagram;

import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.util.Properties;

import org.restlet.data.MediaType;
import org.restlet.data.Reference;
import org.restlet.representation.Variant;
import org.restlet.resource.ResourceException;

import ambit2.core.smiles.OpenBabelDepiction;
import ambit2.rest.query.StructureQueryResource.QueryType;

public class OpenBabelDepict extends AbstractDepict {
    protected static String obabel_home;

    @Override
    protected void doInit() throws ResourceException {
	super.doInit();
	this.getVariants().clear();
	this.getVariants().add(new Variant(MediaType.IMAGE_PNG));
    }

    // obabel -:"CCC(=O)Cl" -O tmp.png -xp 1000
    @Override
    protected BufferedImage getImage(String smiles, int w, int h, String recordType, QueryType type)
	    throws ResourceException {

	try {
	    OpenBabelDepiction ob = new OpenBabelDepiction() {
		/**
			     * 
			     */
		private static final long serialVersionUID = -7104086945548875848L;

		protected String getOBabelHome() {
		    return getOpenBabelHome();
		};
	    };
	    ob.setSize(h);
	    ob.setHydrogens(false);
	    ob.process(smiles);
	    return ob.getImage();
	} catch (Exception x) {
	    throw new ResourceException(x);
	}
    }

    protected String getTitle(Reference ref, String... smiles) throws ResourceException {
	return smiles == null ? getGPlusSnippet() : String.format(
		"SMILES: %s<br><img src='%s' alt='%s' title='%s'>\n%s", smiles, ref, smiles, smiles, getGPlusSnippet());
    }

    @Override
    protected String getGPlusSnippet() {
	return printGPlusSnippet("OpenBabel structure diagram",
		"Chemical structure diagram, generated by http://openbabel.org", null);
    }

    public synchronized String getOpenBabelHome() {
	if (obabel_home == null)
	    try {
		Properties properties = new Properties();
		InputStream in = OpenBabelDepict.class.getClassLoader().getResourceAsStream(
			"ambit2/rest/config/ambit2.pref");
		properties.load(in);
		in.close();
		obabel_home = properties.getProperty(OpenBabelDepiction.OBABEL_HOME);
	    } catch (Exception x) {
		return null;
	    }
	return obabel_home;
    }
}
