PREFIX ot:<http://www.opentox.org/api/1.1#>
PREFIX ota:<http://www.opentox.org/algorithms.owl#>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
	select distinct %s ?Property ?Value
	where {
	%s rdf:type ot:Algorithm.
   OPTIONAL {%s ?Property ?Value}.
	}
order by ?Property ?Value