PREFIX ot:<http://www.opentox.org/api/1.1#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
	select distinct ?vars
	where {
	    <%s> rdf:type ot:Model.
        <%s> ot:independentVariables ?vars. 
   	}