<div class='helptitle' style='font-weight:bold;'>Help: Read Across workflow</div>
<div class='helpcontent'>
Workflow for read across and category formation. <a href="http://echa.europa.eu/support/grouping-of-substances-and-read-across" target="qxternal" class="qxternal">REACH guidance</a>  <br/>
The assessment <a href='#' class='chelp assessment'>?</a> workflow is organized in five main tabs: 
<ol>
<li>Assessment identifier<a href='#' class='chelp a_tab1'></a></li>
<li>Collect structures<a href='#' class='chelp a_tab2'></a></li>
<li>Endpoint data used<a href='#' class='chelp a_tab3'></a></li>
<li>Assessment details<a href='#' class='chelp a_tab4'></a></li>
<li>Endpoint data used<a href='#' class='chelp a_tab5'></a></li>
<li>Report<a href='#' class='chelp a_tab6'></a></li>
</ol>
</div>

<div id="keys" style="display:none;">
  <ul>
    <li><a href="#assessment">Assessment identifier</a></li>
    <li><a href="#a_name">Assessment title</a></li>
    <li><a href="#a_source">Provenance</a></li>
    <li><a href="#a_code">Assessment code</a></li>
    <li><a href="#a_doclink">Assessment Doclink(s)</a></li>
    <li><a href="#a_description">Assessment description</a></li>
    <li><a href="#a_maintainer">Assessment owner</a></li>
    <li><a href="#a_version">Assessment version</a></li>
    <li><a href="#a_version_date">Version dates</a></li>
    <li><a href="#a_license">License or waiver</a></li>
    <li><a href="#a_rightsholder">Assessment rights holder</a></li>
    <li><a href="#a_status">Status</a></li>
    <li><a href="#a_started">Assessment start/complete dates</a></li>
    <li><a href="#a_published">Published status</a></li>
    <li><a href="#a_published_status">Published status</a></li>
    <li><a href="#a_rating">Rating</a></li>
    <li><a href="#bundle_rw">Access rights</a></li>
    
    <li><a href="#a_tab1">Tab1. Assessment identifier</a></li>
    <li><a href="#a_tab2">Tab2. Collect structures</a></li>
    <li><a href="#a_tab3">Tab3. Endpoint data used</a></li>
    <li><a href="#a_tab4">Tab4. Assessment details</a></li>
    <li><a href="#a_tab5">Tab5. Report</a></li>
  </ul>
  <div id="assessment">
  	Assessment ID is automatically generated upon creating an Assessment a new or from an existing template.
  	The Assessment ID is retained when a new version is created, the version is incremented. 
 	<br/>
  	To create a new Assessment, fill in the Assessment identifiers and click Start.
  	<br/>
  	To edit the Assessment identifiers, edit the relevant text fields.
  </div>  
  <div id="a_name">
    The assessment title. This field is mandatory, user should give a meaningful title of the assessment which will  allow easy differentiation between available assessments.
  </div>  
  <div id="a_source">
	Name and URL of the relevant documents about the data origin.  
  </div>  
  <div id="a_code">
    This is a non-mandatory free text field, which allows the user to assign an own code to the assessment for easy retrieval, e.g. company specific code.
  </div>  
  <div id="a_doclink">    
	This is a non-mandatory free text field, where one or more references can be given to documents e.g. hyperlink of an assessment report stored in a document management system
  </div>    
  <div id="a_description">
    This is a non-mandatory free text field, where the user can describe the purpose of the assessment e.g. environmental assessment section.
  </div>    
  <div id="a_maintainer">
    The owner or maintainer of the assessment.
    This field is automatically generated by the system, when the button 'Start assessment' is clicked. The name of the user which has logged on to Ambit is given.
  </div>    
  <div id="a_version">
    The version is generated automatically by the system. Version numbers will be generated consecutively.
    <p> 
    The user has no possibility to change the numbering to avoid confusion. If an assessment version is deleted, the numbering of the other versions remains unchanged.
  </div>    
  <div id="a_version_date">
  	The version `start date` is automatically generated by the system, when the button 'Start assessment' or 'Generate new version' is clicked.
  	<p>
  	The version `last modified on` is automatically generated by the system, giving the date of last modification of data in a version.  
  </div>
  <div id="a_license">
    Enter URI of the  License / Waiver / Rights / Disclaimer <a href="http://dublincore.org/documents/dcmi-terms/#elements-rights" target='qxternal' class='qxternal'>?</a>
    
    <br/>
    A list of Open data licenses / waivers : 
    
    <ul>
    <li><a href='http://www.opendatacommons.org/licenses/pddl/' target='qxternal' class='qxternal'>Public Domain Dedication and License (PDDL) - 'Public Domain for data/databases'</a>
    <li><a href='http://www.opendatacommons.org/licenses/by/' target='qxternal' class='qxternal'>Open Data Commons Attribution (ODC-By) - 'Attribution for data/databases'</a>
    <li><a href='http://www.opendatacommons.org/licenses/odbl/' target='qxternal' class='qxternal'>Open Database License (ODC-ODbL) - 'Attribution Share-Alike for data/databases'</a>
    <li><a href='http://creativecommons.org/publicdomain/zero/1.0/' target='qxternal' class='qxternal'>CC0 1.0 Universal - 'Creative Commons public domain waiver'</a>
    
    <li><a href='http://creativecommons.org/licenses/by-sa/3.0/' target='qxternal' class='qxternal'>Creative Commons Attribution-ShareAlike (CC-BY-SA)</a>
    <li><a href='http://www.gnu.org/copyleft/fdl.html' target='qxternal' class='qxternal'>GNU Free Documentation License (GFDL)</a>
    <li><a href='http://opendatacommons.org/licenses/odbl/1.0/' target='qxternal' class='qxternal'>Open Database License v1.0</a>
    <li><a href='http://opendatacommons.org/licenses/by/1.0/' target='qxternal' class='qxternal'>Open Data Commons Attribution License (ODC-By) v1.0</a>
    
	</ul>
   
  </div>   
  
  <div id="bundle_rw">
  	Read/Write access. 
  	Start typing in. The user name will appear.
  	<p>
  	Note: This is under development, only admin and guest names are available for demonstration purposes!
  </div>
  <div id="a_rightsholder">
    <a href="http://dublincore.org/documents/dcmi-terms/#terms-rightsHolder" target='qxternal' class='qxternal'>Rights holder</a> A person or organization owning or managing rights over the resource. 
  </div>
  <div id="a_status">
    Status. Not supported yet
    This is a mandatory free text field. Owner has to give information to allow differentiation between the different versions
  </div>
  <div id="a_started">
    Version start date: This is automatically generated by the system.
    <br/>
    Version last modified on: This is automatically generated by the system, giving the date of last modification of the data in a version.
  </div>
  <div id="a_rating">
    1 to 10 stars
  </div>         
  <div id="a_published">
    This a mandatory field, where the user has to select a value from a predefined pick list: yes, no.
  </div>
  <div id="a_published_status">
    One of : published, draft, archived
  </div>                  
  <div id="a_tab1">
	This tab. Allows to create new assessment or update the fields of an existing assessment.
  </div>
  <div id="a_tab2">
	<ul>
	<li>Search by identifiers: CAS, EC, Name, structure, substructure, similarity</li>
	<li>Tag the structure as initial target <b>T</b> or source <b>S</b>. Once tagged, the structure appears in the list of collected structures</li>
	<li>List collected structures</li>
	</ul>
  </div>
  <div id="a_tab3">
	For each structure of the list show the related substances and endpoint data.  
	<br/>
	By default shows only the endpoints available for the selected substances only. The <i>Show All</i> checkbox will show the full list.
	<br/>
	The assessor has to check mark those endpoints which should be displayed in the data matrix.
	<br/>
	Selecting at least one substance and endpoint will enable the <i>Assessment details</i> tab.
  </div>
  <div id="a_tab4">
  	The <b>data matrix</b> is separated into different  matrices, called <i>initial</i>, <i>working</i>, and <i>final</i>.
  	<ul>
  	<li>The <b>initial</b> matrix is generated automatically by the selection of substances and endpoints. Can not be edited.</li>
  	<li>The <b>working</b> matrix is generated upon user request from the initial matrix. Data points may be added or removed.</li>
  	<li>The <b>final</b> matrix is generated upon user request from the working matrix. Can not be edited.</li> 
  	</ul> 

  </div>      
  <div id="a_tab5">
	Not supported yet.
   </div>        
  
</div>      