name: Build an ambit-docker package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: >-
        mvn
        -B
        -f ambit2-apps/ambit2-www/pom.xml
        clean
        buildnumber:create
        package
        -P http
        -P docker_generic
        -DskipTests=true

    - name: Publish to GitHub Packages
      run: >-
        mvn
        -B
        -f ambit2-apps/ambit2-www/pom.xml
        -s $GITHUB_WORKSPACE/settings.xml
        deploy
        -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/ideaconsult/ambit-mirror
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Send Discord Notification
      uses: sarisia/actions-status-discord@v1.7.0
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
